### ISSUE TITLE
Config anpassen

### ISSUE THREAD

**Issue by marcusg** [hausgold/docker-ejabberd#1]
Die default config muss erweitert werden, damit wir Message Archive haben und die Berechtigungen anpassen:

```
modules:
  mod_mam:        
    request_activates_archiving: true
    iqdisc: one_queue
    default: always
    db_type: mnesia

  mod_muc:
    ## Nur admins sollen räume erstellen und ändern dürfen
    ## host: "conference.@HOST@"
    access: muc
    ## access_create: muc_create
    access_create: muc_admin
    ## access_persistent: muc_create
    access_persistent: muc_admin
    access_admin: muc_admin

    ## Räume sollen standardmäßig persistent sein und Speicherung aktiviert haben
    default_room_options:
      allow_subscription: true
      persistent: true
      mam: true
```
